Repository Mu-necting/Mu-necting_Server_V4, pull requests merged in 2024-08, with the labels that each got.

#11 댓글 관련 API 작성 완료
  build.gradle
  src/main/java/com/munecting/api/domain/comment/controller/CommentController.java
  src/main/java/com/munecting/api/domain/comment/dao/CommentRepository.java
  src/main/java/com/munecting/api/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/munecting/api/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/munecting/api/domain/comment/entity/Comment.java
  src/main/java/com/munecting/api/domain/comment/service/CommentService.java
  src/main/java/com/munecting/api/global/common/dto/response/Status.java
  src/main/java/com/munecting/api/global/common/util/StringToLocalDateTimeConverter.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#14 Setting/#6 로그인 설정
  build.gradle
  src/main/java/com/munecting/api/domain/user/controller/UserController.java
  src/main/java/com/munecting/api/domain/user/dto/Role.java
  src/main/java/com/munecting/api/domain/user/dto/SocialType.java
  src/main/java/com/munecting/api/domain/user/dto/UserRegisterDto.java
  src/main/java/com/munecting/api/domain/user/dto/UserResponseDto.java
  src/main/java/com/munecting/api/domain/user/entity/User.java
  src/main/java/com/munecting/api/domain/user/repository/UserRepository.java
  src/main/java/com/munecting/api/domain/user/service/UserService.java
  src/main/java/com/munecting/api/global/Redis/entity/RefreshEntity.java
  src/main/java/com/munecting/api/global/Redis/repository/RefreshRepository.java
  src/main/java/com/munecting/api/global/common/dto/response/Status.java
  src/main/java/com/munecting/api/global/config/EmailConfig.java
  src/main/java/com/munecting/api/global/config/RedisConfig.java
  src/main/java/com/munecting/api/global/config/SecurityConfig.java
  src/main/java/com/munecting/api/global/jwt/controller/ReissueRefreshTokenController.java
  src/main/java/com/munecting/api/global/jwt/filter/JWTFilter.java
  src/main/java/com/munecting/api/global/jwt/util/JWTUtil.java
  src/main/java/com/munecting/api/global/login/filter/CustomLoginFilter.java
  src/main/java/com/munecting/api/global/login/filter/CustomLogoutFilter.java
  src/main/java/com/munecting/api/global/login/handler/LoginFailureHandler.java
  src/main/java/com/munecting/api/global/login/handler/LoginSuccessHandler.java
  src/main/java/com/munecting/api/global/login/service/CustomUserDetailService.java
  src/main/java/com/munecting/api/global/oauth2/dto/GoogleResponse.java
  src/main/java/com/munecting/api/global/oauth2/dto/KakaoResponse.java
  src/main/java/com/munecting/api/global/oauth2/dto/NaverResponse.java
  src/main/java/com/munecting/api/global/oauth2/dto/OAuth2Response.java
  src/main/java/com/munecting/api/global/oauth2/dto/SpotifyResponse.java
  src/main/java/com/munecting/api/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/munecting/api/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/munecting/api/global/oauth2/service/CustomOAuth2User.java
  src/main/java/com/munecting/api/global/oauth2/service/CustomOAuth2UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙️setting

#17 위치기반 음악 업로드 관련 API 작성 완료
  build.gradle
  src/main/java/com/munecting/api/domain/address/controller/AddressController.java
  src/main/java/com/munecting/api/domain/address/service/AddressService.java
  src/main/java/com/munecting/api/domain/uploadedMusic/controller/MusicController.java
  src/main/java/com/munecting/api/domain/uploadedMusic/dao/UploadedMusicRepository.java
  src/main/java/com/munecting/api/domain/uploadedMusic/dto/MusicRequestDto.java
  src/main/java/com/munecting/api/domain/uploadedMusic/dto/UploadedMusicResponseDto.java
  src/main/java/com/munecting/api/domain/uploadedMusic/entity/UploadedMusic.java
  src/main/java/com/munecting/api/domain/uploadedMusic/service/MusicService.java
  src/main/java/com/munecting/api/global/common/dto/response/GlobalExceptionHandler.java
  src/main/java/com/munecting/api/global/config/RestClientConfig.java
  src/main/java/com/munecting/api/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#24 like domain 기본 세팅
  src/main/java/com/munecting/api/domain/like/controller/LikeController.java
  src/main/java/com/munecting/api/domain/like/dao/LikeRepository.java
  src/main/java/com/munecting/api/domain/like/entity/Like.java
  src/main/java/com/munecting/api/domain/like/service/LikeService.java
Labels: :sparkles: feat, ⚙️setting

#26 회원 로그아웃 및 탈퇴 API 구현 완료, Comment service 메소드 리팩토링
  src/main/java/com/munecting/api/domain/comment/controller/CommentController.java
  src/main/java/com/munecting/api/domain/comment/dao/CommentRepository.java
  src/main/java/com/munecting/api/domain/comment/service/CommentService.java
  src/main/java/com/munecting/api/domain/like/dao/LikeRepository.java
  src/main/java/com/munecting/api/domain/like/service/LikeService.java
  src/main/java/com/munecting/api/domain/uploadedMusic/dao/UploadedMusicRepository.java
  src/main/java/com/munecting/api/domain/uploadedMusic/service/MusicService.java
  src/main/java/com/munecting/api/domain/user/controller/AuthController.java
  src/main/java/com/munecting/api/domain/user/controller/UserController.java
  src/main/java/com/munecting/api/domain/user/dto/request/LoginRequestDto.java
  src/main/java/com/munecting/api/domain/user/dto/request/LogoutRequestDto.java
  src/main/java/com/munecting/api/domain/user/dto/request/RefreshTokenRequestDto.java
  src/main/java/com/munecting/api/domain/user/dto/response/UserTokenResponseDto.java
  src/main/java/com/munecting/api/domain/user/service/AuthService.java
  src/main/java/com/munecting/api/domain/user/service/UserService.java
  src/main/java/com/munecting/api/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/munecting/api/global/auth/interceptor/UserAuthorizationInterceptor.java
  src/main/java/com/munecting/api/global/auth/jwt/JwtProvider.java
  src/main/java/com/munecting/api/global/auth/resolver/UserIdArgumentResolver.java
  src/main/java/com/munecting/api/global/auth/user/UserPrincipalDetails.java
  src/main/java/com/munecting/api/global/common/dto/response/Status.java
  src/main/java/com/munecting/api/global/config/WebConfig.java
Labels: :sparkles: feat, :recycle: refactor

#28 존재하지 않는 엔드포인트 요청 시 발생하는 에러 응답 핸들링 완료
  src/main/java/com/munecting/api/global/error/handler/GlobalExceptionHandler.java
Labels: :sparkles: feat

#32 좋아요 관련 API 구현 완료
  src/main/java/com/munecting/api/domain/comment/dao/CommentRepository.java
  src/main/java/com/munecting/api/domain/comment/service/CommentService.java
  src/main/java/com/munecting/api/domain/like/controller/LikeController.java
  src/main/java/com/munecting/api/domain/like/dao/LikeRepository.java
  src/main/java/com/munecting/api/domain/like/dto/response/AddTrackLikeResponseDto.java
  src/main/java/com/munecting/api/domain/like/dto/response/DeleteTrackLikeResponseDto.java
  src/main/java/com/munecting/api/domain/like/dto/response/GetLikedTrackListResponseDto.java
  src/main/java/com/munecting/api/domain/like/dto/response/GetLikedTrackResponseDto.java
  src/main/java/com/munecting/api/domain/like/dto/response/LikedTrackArtistResponseDto.java
  src/main/java/com/munecting/api/domain/like/entity/Like.java
  src/main/java/com/munecting/api/domain/like/service/LikeService.java
  src/main/java/com/munecting/api/domain/spotify/dto/SpotifyDtoMapper.java
  src/main/java/com/munecting/api/domain/spotify/service/SpotifyApiCall.java
  src/main/java/com/munecting/api/domain/spotify/service/SpotifyService.java
  src/main/java/com/munecting/api/domain/track/controller/TrackController.java
  src/main/java/com/munecting/api/domain/track/dto/response/GetTrackDetailsResponseDto.java
  src/main/java/com/munecting/api/domain/track/service/TrackService.java
  src/main/java/com/munecting/api/domain/uploadedMusic/service/MusicService.java
  src/main/java/com/munecting/api/domain/user/service/UserService.java
Labels: :sparkles: feat

#33 아이디 토큰 검증 추가 및 리팩토링 완료
  src/main/java/com/munecting/api/domain/oidc/dto/OidcPublicKey.java
  src/main/java/com/munecting/api/domain/oidc/dto/OidcPublicKeyList.java
  src/main/java/com/munecting/api/domain/oidc/dto/OidcUserInfo.java
  src/main/java/com/munecting/api/domain/oidc/factory/OidcFactory.java
  src/main/java/com/munecting/api/domain/oidc/keyManagement/PublicKeyProvider.java
  src/main/java/com/munecting/api/domain/oidc/keyManagement/client/ApplePublicKeyClient.java
  src/main/java/com/munecting/api/domain/oidc/keyManagement/client/KakaoPublicKeyClient.java
  src/main/java/com/munecting/api/domain/oidc/keyManagement/client/PublicKeyClient.java
  src/main/java/com/munecting/api/domain/oidc/service/OidcService.java
  src/main/java/com/munecting/api/domain/oidc/strategy/AbstractOidcStrategy.java
  src/main/java/com/munecting/api/domain/oidc/strategy/OidcStrategy.java
  src/main/java/com/munecting/api/domain/oidc/strategy/impl/AppleOidcStrategy.java
  src/main/java/com/munecting/api/domain/oidc/strategy/impl/GoogleOidcStrategy.java
  src/main/java/com/munecting/api/domain/oidc/strategy/impl/KakaoOidcStrategy.java
  src/main/java/com/munecting/api/domain/user/dao/UserRepository.java
  src/main/java/com/munecting/api/domain/user/entity/User.java
  src/main/java/com/munecting/api/domain/user/service/AuthService.java
  src/main/java/com/munecting/api/global/auth/jwt/JwtProvider.java
  src/main/java/com/munecting/api/global/auth/oidc/provider/AbstractOidcProvider.java
  src/main/java/com/munecting/api/global/auth/oidc/provider/AppleAuthProvider.java
  src/main/java/com/munecting/api/global/auth/oidc/provider/KakaoAuthProvider.java
  src/main/java/com/munecting/api/global/auth/oidc/provider/OidcProvider.java
  src/main/java/com/munecting/api/global/auth/oidc/provider/OidcProviderFactory.java
  src/main/java/com/munecting/api/global/auth/oidc/publicKey/client/ApplePublicKeyClient.java
  src/main/java/com/munecting/api/global/auth/oidc/publicKey/client/KakaoPublicKeyClient.java
  src/main/java/com/munecting/api/global/auth/oidc/publicKey/client/PublicKeyClient.java
  src/main/java/com/munecting/api/global/auth/user/UserPrincipalDetails.java
  src/main/resources/application.yml
Labels: :recycle: refactor
