Repository Mu-necting/Mu-necting_Server_V4, pull requests merged in 2024-11, with the labels that each got.

#53 프로필 업데이트 API 구현 완료
  build.gradle
  src/main/java/com/munecting/api/domain/user/controller/UserController.java
  src/main/java/com/munecting/api/domain/user/dao/UserRepository.java
  src/main/java/com/munecting/api/domain/user/dao/UuidRepository.java
  src/main/java/com/munecting/api/domain/user/dto/request/UpdateProfileRequestDto.java
  src/main/java/com/munecting/api/domain/user/dto/response/UpdateProfileResponseDto.java
  src/main/java/com/munecting/api/domain/user/entity/User.java
  src/main/java/com/munecting/api/domain/user/entity/Uuid.java
  src/main/java/com/munecting/api/domain/user/service/AuthService.java
  src/main/java/com/munecting/api/domain/user/service/UserProfileImageService.java
  src/main/java/com/munecting/api/domain/user/service/UserService.java
  src/main/java/com/munecting/api/domain/user/service/UuidService.java
  src/main/java/com/munecting/api/global/aws/s3/AmazonS3Manager.java
  src/main/java/com/munecting/api/global/common/dto/response/Status.java
  src/main/java/com/munecting/api/global/config/AmazonConfig.java
  src/main/java/com/munecting/api/global/config/CorsConfig.java
  src/main/java/com/munecting/api/global/error/exception/InternalServerException.java
  src/main/java/com/munecting/api/global/error/exception/InvalidValueException.java
  src/main/java/com/munecting/api/global/error/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#54 Comment, UploadedMusic에 인증 및 user 정보 리팩토링 완료
  build.gradle
  src/main/java/com/munecting/api/domain/comment/controller/CommentController.java
  src/main/java/com/munecting/api/domain/comment/dto/request/CommentRequestDto.java
  src/main/java/com/munecting/api/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/munecting/api/domain/comment/entity/Comment.java
  src/main/java/com/munecting/api/domain/comment/service/CommentService.java
  src/main/java/com/munecting/api/domain/like/controller/LikeController.java
  src/main/java/com/munecting/api/domain/uploadedMusic/controller/MusicController.java
  src/main/java/com/munecting/api/domain/uploadedMusic/dto/request/MusicRequestDto.java
  src/main/java/com/munecting/api/domain/uploadedMusic/dto/response/UploadedMusicResponseDto.java
  src/main/java/com/munecting/api/domain/uploadedMusic/entity/UploadedMusic.java
  src/main/java/com/munecting/api/domain/uploadedMusic/service/MusicService.java
  src/main/java/com/munecting/api/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/munecting/api/domain/user/service/UserService.java
  src/main/java/com/munecting/api/global/common/dto/response/Status.java
  src/main/java/com/munecting/api/global/config/AppConfig.java
Labels: :recycle: refactor

#57 유저 프로필 조회 API 구현 완료
  src/main/java/com/munecting/api/domain/user/controller/UserController.java
  src/main/java/com/munecting/api/domain/user/dto/response/GetProfileResponseDto.java
  src/main/java/com/munecting/api/domain/user/service/UserService.java
Labels: :sparkles: feat

#59 회원가입 시 닉네임 생성 로직 수정 완료
  src/main/java/com/munecting/api/domain/oidc/dto/OidcUserInfo.java
  src/main/java/com/munecting/api/domain/oidc/strategy/impl/AppleOidcStrategy.java
  src/main/java/com/munecting/api/domain/oidc/strategy/impl/GoogleOidcStrategy.java
  src/main/java/com/munecting/api/domain/oidc/strategy/impl/KakaoOidcStrategy.java
  src/main/java/com/munecting/api/domain/user/entity/User.java
  src/main/java/com/munecting/api/domain/user/service/AuthService.java
  src/main/java/com/munecting/api/domain/user/service/UserNicknameService.java
  src/main/java/com/munecting/api/domain/user/service/UserService.java
  src/main/java/com/munecting/api/global/common/dto/response/Status.java
Labels: :sparkles: feat, :hammer_and_wrench: fix

#60 회원 탈퇴 엔드포인트 수정 완료
  src/main/java/com/munecting/api/domain/user/controller/UserController.java
  src/main/java/com/munecting/api/global/auth/interceptor/UserAuthorizationInterceptor.java
  src/main/java/com/munecting/api/global/config/WebConfig.java
Labels: :hammer_and_wrench: fix
